# -*- coding: utf-8 -*-
"""CIS5300-OL-hw3-v0.2_rjiang.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18xHfuTwgJdB5Q7KE-2oK7_Y-BfGvO0f9

# Homework 3: N-Gram Language Models

## Total Points: 95 + 5 bonus
- **Overview**: In the textbook, language modeling was defined as the task of predicting the next word in a sequence given the previous words. In this assignment, we will focus on the related problem of predicting the next character in a sequence given the previous characters.

- **Learning goals**:
    - Understand how to compute language model probabilities using maximum likelihood estimation.
    - Implement basic smoothing, back-off and interpolation.
    - Have fun using a language model to probabilistically generate texts.
    - Use a set of language models to perform text classification.

- **Data**: We will provide you with training and development data that has been manually labeled. We will also give you a test set without labels. You will build a classifier to predict the labels on our test set. You can upload your classifier’s predictions to Gradescope. We will score its predictions and maintain a leaderboard showing whose classifier has the best performance.

- **Delieverables:** This assignment has several deliverables:
    - Your implementations for the functions in the skeleton code (this notebook)
    - Answers to all questions labeled as `Answer #.#` in a file named `report.pdf`
    - Your model’s output for the test set (your model will be ranked on a leaderboard against the other students’ outputs)

- **Grading**: We will use the auto-grading system called `PennGrader`. To complete the homework assignment, you should implement anything marked with `#TODO` and run the cell with `#PennGrader` note. **There will be no hidden tests in this assignment.** In other words, you will know your score once you finish all the `#TODO` and run all the `#PennGrader` tests!


## Recommended Readings
- [Language Modeling with N-grams](https://web.stanford.edu/~jurafsky/slp3/3.pdf). Dan Jurafsky and James H. Martin. Speech and Language Processing (3rd edition draft) .
- [A Bit of Progress in Language Modeling](https://arxiv.org/abs/cs/0108005). Joshua Goodman. Computer Speech and Language .
- [The Unreasonable Effectiveness of Character-level Language Models](http://nbviewer.jupyter.org/gist/yoavg/d76121dfde2618422139). Yoav Goldberg. Response to Andrej Karpathy's blog post. 2015.
- [Language Independent Authorship Attribution using Character Level Language Models](http://www.aclweb.org/anthology/E/E03/E03-1053.pdf). Fuchun Pen, Dale Schuurmans, Vlado Keselj, Shaojun Wan. EACL 2003.

## To get started, **make a copy** of this colab notebook into your google drive!

## Setup 1: PennGrader Setup [4 points]
"""

# Commented out IPython magic to ensure Python compatibility.
# ## DO NOT CHANGE ANYTHING, JUST RUN
# %%capture
# !pip install penngrader-client

# Commented out IPython magic to ensure Python compatibility.
#  %%writefile notebook-config.yaml

grader_api_url: 'https://23whrwph9h.execute-api.us-east-1.amazonaws.com/default/Grader23'
grader_api_key: 'flfkE736fA6Z8GxMDJe2q8Kfk8UDqjsG3GVqOFOa'

!cat notebook-config.yaml|

from penngrader.grader import *

## TODO - Start
STUDENT_ID = 62502470 # YOUR PENN-ID GOES HERE AS AN INTEGER#
## TODO - End

SECRET = STUDENT_ID
grader = PennGrader('notebook-config.yaml', 'CIS5300_OL_23Su_HW3', STUDENT_ID, SECRET)

# check if the PennGrader is set up correctly
# do not chance this cell, see if you get 4/4!
name_str = 'Rui Jiang'
grader.grade(test_case_id = 'name_test', answer = name_str)

"""## Setup 2: Dataset / Packages
- **Run the following cells without changing anything!**
- [Loading dataset from huggingface](https://huggingface.co/docs/datasets/v1.8.0/loading_datasets.html#from-local-files)
"""

import math, random
from collections import Counter
from dill.source import getsource

## DO NOT CHANGE ANYTHING, JUST RUN

def get_class_source(cls):
    import re
    class_name = cls.__name__
    from IPython import get_ipython
    ipython = get_ipython()
    inputs = ipython.user_ns['In']
    pattern = re.compile(r'^\s*class\s+{}\b'.format(class_name))
    for cell in reversed(inputs):
        if pattern.search(cell):
            return cell
    return None

from pathlib import Path
import os
print('/content/cities_train.zip exist is {} '.format(os.path.exists('/content/cities_train.zip')))
print('/content/cities_val.zip exist is {} '.format(os.path.exists('/content/cities_val.zip')))
print('/content/cities_test.txt exist is {} '.format(os.path.exists('/content/cities_test.txt')))
print('/content/nytimes_article.txt exist is {} '.format(os.path.exists('/content/nytimes_article.txt')))
print('/content/shakespeare_sonnets.txt exist is {} '.format(os.path.exists('/content/shakespeare_sonnets.txt')))
print('/content/shakespeare_input.txt exist is {} '.format(os.path.exists('/content/shakespeare_input.txt')))

!gdown 19ZFc_nFF3T-LTI9rxXUy1XyMaoGSzN3T # https://drive.google.com/file/d/19ZFc_nFF3T-LTI9rxXUy1XyMaoGSzN3T/view?usp=share_link
!unzip -o cities_train.zip
!gdown 1BH9qhvR7POqmGPOPadqADv-NxdGBgyzu # https://drive.google.com/file/d/1BH9qhvR7POqmGPOPadqADv-NxdGBgyzu/view?usp=sharing
!unzip -o cities_val.zip
!gdown 1mz6EdH-4pOwr-o3lHDlh1SS7oRdydNr1 # https://drive.google.com/file/d/1mz6EdH-4pOwr-o3lHDlh1SS7oRdydNr1/view?usp=sharing
!gdown 11es6r9fVz_wf_Q2T7oP2IQDkAAmhtzf4 # https://drive.google.com/file/d/11es6r9fVz_wf_Q2T7oP2IQDkAAmhtzf4/view?usp=share_link
!gdown 19P37gR_XDup-h3a4LdKtQWbdM-lGPqin # https://drive.google.com/file/d/19P37gR_XDup-h3a4LdKtQWbdM-lGPqin/view?usp=sharing
!gdown 1kKfh2oaxinBPVwWaux6FA9TerqAH5nHw # https://drive.google.com/file/d/1kKfh2oaxinBPVwWaux6FA9TerqAH5nHw/view?usp=sharing

"""# Section 0: Generating N-Grams [5 points]
- **Problem 0:** Write a function `ngrams(n, text)` that produces a list of all n-grams of the specified size from the input text. Each n-gram should consist of a 2-element tuple `(context, char)`, where the context is itself an n-length string comprised of the n characters preceding the current character. The sentence should be padded with n ~ characters at the beginning (we’ve provided you with `start_pad(n)` for this purpose). If n=0 , all contexts should be empty strings. You may assume that n≥0.

```
>>> ngrams(1, 'abc')
[('~', 'a'), ('a', 'b'), ('b', 'c')]

>>> ngrams(2, 'abc')
[('~~', 'a'), ('~a', 'b'), ('ab', 'c')]
```
"""

### DO NOT CHANGE ###
def start_pad(n):
    ''' Returns a padding string of length n to append to the front of text
        as a pre-processing step to building n-grams '''
    return '~' * n
### DO NOT CHANGE ###

def ngrams(n, text):
    ''' Returns the ngrams of the text as tuples where the first element is
        the length-n context and the second is the character '''

    ## AUTOGRADER HELPER ##
    def start_pad(n):
        ''' Returns a padding string of length n to append to the front of text
            as a pre-processing step to building n-grams '''
        return '~' * n
    ## AUTOGRADER HELPER ##


    ## TODO: create n-grams given the text
    padding = start_pad(n)
    new_text = padding+text
    text_len = len(text)

    padded_text = start_pad(n) + text
    result = []
    for i in range(text_len):
      result.append((new_text[i:n+i], new_text[n+i]))
    return result

result = ngrams(2, "ab")
result

result = ngrams(0, "ab")
result

result = ngrams(1, "ab")
result

# PennGrader - DO NOT CHANGE
grader.grade(test_case_id = 'test_q0_ngrams', answer = getsource(ngrams))

"""# Section 1: Creating an N-Gram Model [36 points]
In this section, you will build a simple n-gram language model that can be used to generate random text resembling a source document. Your use of external code should be limited to built-in Python modules, which excludes, for example, `NumPy` and `NLTK`.

"""

from collections import defaultdict
import math
COUNT_KEY = 'count'
CHARS_KEY = 'chars'

class NgramModel(object):
    ''' A basic n-gram model using add-k smoothing '''

    def __init__(self, n, k = 0):
        # print("__init__")
        # About `k`: you don't need to worry about it for problem 1.1, it is something you will need in problem 2.1
        self.k = k

        # contexts is a dictionary with the context as keys and corresponding value is a dictionary of count and
        # chars which is a dictionary of characters as key and it's count as value.
        # Please do not change the format of storing the counts and characters, the autograder uses this structure
        # For example:
        # if the context is 'ab' with count=3 and characters following it are 'a' and 'b' with counts 2 and 1 respectively
        # then the context dictionary would look like this:
        # {
        #   'ab' : {'count': 3,'chars': {'a' : 2, 'b' : 1}},
        #   'aa' : {...},
        #   ...
        # }
        self.contexts = {}

        ## TODO 1.1 - see problem 1.1
        self.n = n
        self.vocab = set()

    def get_vocab(self):
        # print("get_vocab")
        ''' Returns the set of characters in the vocab '''
        return self.vocab

    def get_context(self):
        # print("get_context")
        ''' Returns the dictionary for context '''
        return self.contexts

    def update(self, text):
        ''' Updates the model n-grams based on text '''
        ## TODO 1.2 - see problem 1.2
        # print("get_update")
        if self.n == 0:
            if '' in self.contexts:
                self.contexts[''][COUNT_KEY] = self.contexts[''][COUNT_KEY] + len(text)
            else:
                self.contexts[''] = dict()
                self.contexts[''][COUNT_KEY] = len(text)
                self.contexts[''][CHARS_KEY] = defaultdict(int)
            for letter in text:
                self.contexts[''][CHARS_KEY][letter] = self.contexts[''][CHARS_KEY][letter] + 1
        else:
            ngrams_context = ngrams(self.n, text)
            # print("ngrams_context is {}".format(ngrams_context))
            for ngram_item in ngrams_context:
                pre_context, cur_letter = ngram_item
                if pre_context in self.contexts:
                    self.contexts[pre_context][COUNT_KEY] += 1
                else:
                    self.contexts[pre_context] = dict()
                    self.contexts[pre_context][COUNT_KEY] = 1
                    self.contexts[pre_context][CHARS_KEY] = defaultdict(int)
                self.contexts[pre_context][CHARS_KEY][cur_letter] += 1
        # update vocalbulary
        for key, value in self.contexts.items():
            # self.vocabulary.update(key)
            self.vocab.update(value[CHARS_KEY].keys())

        # print("get_vocab self.vocab is {}".format(self.vocab))
        if '~' in self.vocab:
            self.vocab.remove('~')
        return

    def prob(self, context, char):
        # print("prob")
        ''' Returns the probability of char appearing after context '''
        if self.k == 0:
            ## TODO 1.2 - see problem 1.2
            # print("self.prob self.contexts {} context is {} char is {}".format(self.contexts, context, char))

            if context not in self.contexts:
                # print("context is not in sefl.contexts ")
                # print("self.vocabulary is {}".format(self.vocabulary))
                return 1/(len(self.get_vocab()))
            context_count = self.contexts[context][COUNT_KEY]
            char_count = self.contexts[context][CHARS_KEY][char]
            return char_count / context_count
        else:
            ## TODO 2.1 - see problem 2.1 Smoothing
            if context not in self.contexts:
                return 1/(len(self.get_vocab()))
            v_count = len(self.get_vocab())
            sum_n = 0
            char_count = self.k
            for key in self.contexts[context][CHARS_KEY]:
                if key == char:
                    char_count += self.contexts[context][CHARS_KEY][key]
                sum_n += self.contexts[context][CHARS_KEY][key]
            return char_count / (sum_n + self.k * v_count)

    def random_char(self, context):
        # print("random_char")
        ''' Returns a random character based on the given context and the
            n-grams learned by this model '''
        ## TODO 1.3 - see problem 1.3
        if context == '':
            # select one letter radomly from vacabulary
            r = random.random()
            voc = sorted(list(self.get_vocab()))
            return voc[int(r * len(voc))]

        if context not in self.contexts:
            voc = sorted(list(self.get_vocab()))
            r = random.random()
            # print("voc is {} r is {}".format(voc, r))
            return voc[int(r * len(voc))]

        total_count = self.contexts[context][COUNT_KEY]
        keys_list = sorted(list(self.contexts[context][CHARS_KEY].keys()))
        prob_range = {} # key is letters, value is tuple (lower range, uppper range) for probabilities
        prob = 0.0
        for key in keys_list:
            key_prob = self.contexts[context][CHARS_KEY][key] / total_count
            prob_range[key] = (prob, prob + key_prob)
            prob += key_prob
        # print("prob_range is {}".format(prob_range))
        r = random.random()
        for key in keys_list:
            if r >= prob_range[key][0] and r < prob_range[key][1]:
                return key

    def random_text(self, length):
        # print("random_text")
        ''' Returns text of the specified character length based on the
            n-grams learned by this model '''
        ## TODO 1.4 - see problem 1.4
        result = []
        context = ''

        for i in range(length):
            context = ''
            if len(result) < (self.n):
                context = '~' * (self.n-len(result)) + ''.join(result)
            else:
                # print("context is {}".format(result[(0-self.n):]))
                context = ''.join(result[(0-self.n):])
            # print("context is {}".format(context))
            result.append(self.random_char(context))
        return ''.join(result)

    def perplexity(self, text):
        # print("perplexity")
        ''' Returns the perplexity of text based on the n-grams learned by
            this model '''
        ## TODO 2.2 - see problem 2.2
        # return 0.56
        grams = ngrams(self.n, text)
        # print("grams is {}".format(grams))
        sum = 0
        for gram in grams:
            # print("gram is {}".format(gram))
            if gram[0] not in self.contexts.keys():
                # print("gram {} is not in contexts".format(gram[0]))
                return math.inf
            else:
                if gram[1] not in self.contexts[gram[0]][CHARS_KEY].keys():
                    return math.inf
                prob = self.prob(gram[0], gram[1])
                # print("gram[0] is {} gram[1] is {} prob is {}".format(gram[0], gram[1], prob))
                log_new = math.log2(prob)
                # print("gram {} prob is {} log_new {}".format(gram, prob, log_new))
                sum += log_new

        avg = sum / len(grams)
        # print("avg is {} len of gram is {}".format(avg, len(grams)))
        return math.pow(2, 0 - avg)

"""## 1.1 Initialization [3 points]
In the `NgramModel` class, write an initialization method `__init__(self, n, k)` which stores the order n of the model and initializes any necessary internal variables. Then write a method `get_vocab(self)` that returns the vocab (this is the `set` of all characters used by this model).

- **Problem 1.1:** finish `__init__(self, n, k)` and `get_vocab(self)` [3 points]
"""

# PennGrader - DO NOT CHANGE
ngram_model = NgramModel(1, 0)
grader.grade(test_case_id = 'test_q11_init_get_vocab', answer = get_class_source(NgramModel))

"""## 1.2 Update and Calculate Probabilities [15 points]
Write a method `update(self, text)` which computes the n-grams for the input sentence and updates the internal counts. Also write a method `prob(self, context, char)` which accepts an n-length string representing a context and a character, and returns the probability of that character occuring, given the preceding context. If you encounter a novel `context`, the probability of any given `char` should be 1/V where V is the size of the vocab.

- **Problem 1.2:** finish `update(self, text)` and `prob(self, context, char)` [15 points]
"""

# PennGrader - DO NOT CHANGE
all_test_cases = [
    (1, ['abab', 'abcd'], [('b','c'), ('a', '~')]),
    (2, ['ababa', 'abcdddd', 'babcdabag'], [('ab', 'a'), ('ad', 'b')]),
    (3, ['ababa', 'abcdddd', 'babcdabag'], [('ddd', 'd'   ), ('~~c', 'f')]),
    (2, ['abc'], [('~a', 'b'), ('~~', 'a')])
]

all_test_results = []
for test_data in all_test_cases:
    nm = NgramModel(test_data[0], 0)
    for text in test_data[1]:
        nm.update(text)
    vocab = nm.get_vocab()
    probs = []
    for prob_check in test_data[2]:
        prob = nm.prob(prob_check[0], prob_check[1])
        probs.append(prob)
    all_test_results.append((vocab, probs))

# reload_grader()
grader.grade(test_case_id = 'test_q12_update_prob', answer = all_test_results)

"""## 1.3 Random Character [6 points]

Write a method `random_char(self, context)` which returns a random character according to the probability distribution determined by the given context. Specifically, let $V=\langle v_1,v_2, \cdots, v_n \rangle$ be the vocab, sorted according to Python's natural lexicographic ordering, and let $r$ be a random number between 0 and 1. Your method should return the character $v_i$ such that:
$$
\sum_{j=1}^{i-1} P(v_j\ |\ \text{context}) \le r < \sum_{j=1}^i P(v_j\ | \ \text{context}).
$$
You should use a single call to the `random.random()` function to generate $r$, for example:
```
>>> m = NgramModel(0, 0)
>>> m.update('abab')
>>> m.update('abcd')
>>> random.seed(1)
>>> [m.random_char('') for i in range(25)]
['a', 'c', 'c', 'a', 'b', 'b', 'b', 'c', 'a', 'a', 'c', 'b', 'c', 'a', 'b', 'b', 'a', 'd', 'd', 'a', 'a', 'b', 'd', 'b', 'a']
```

- **Problem 1.3:** finish `random_char(self, context)` [6 points]
"""

# PennGrader - DO NOT CHANGE
corpus = ['ababa', 'abcdddd', 'babcdabag', 'dbaa', 'dbab']
nm = NgramModel(1, 0)
for text in corpus:
    nm.update(text)

random_seed_lst = [2, 3, 4]
random_char_lst = []
for seed in random_seed_lst:
    random.seed(seed)
    random_char = [nm.random_char('') for i in range(25)]
    random_char_lst.append(random_char)

grader.grade(test_case_id = 'test_q13_rand_char', answer = random_char_lst)

"""## 1.4 Random Text [6 points]
In the `NgramModel` class, write a method `random_text(self, length)` which returns a string of characters chosen at random using the `random_char(self, context)` method. Your starting context should always be $n$ ~ characters, and the context should be updated as characters are generated. If $n=0$, your context should always be the empty string. You should continue generating characters until you've produced the specified number of random characters, then return the full string.

```python
>>> m = NgramModel(1, 0)
>>> m.update('abab')
>>> m.update('abcd')
>>> random.seed(1)
>>> m.random_text(25)
abcdbabcdabababcdddabcdba
```

- **Problem 1.4:** finish `random_text(self, length)` [6 points]
"""

# PennGrader - DO NOT CHANGE
corpus = ['ababa', 'abcdddd', 'babcdabag', 'dbaa', 'dbab']
nm = NgramModel(1, 0)
for text in corpus:
    nm.update(text)

random_seed_lst = [42, 43, 44]
random_text_lst = []
for seed in random_seed_lst:
    random.seed(seed)
    random_text = nm.random_text(25)
    random_text_lst.append(random_text)

grader.grade(test_case_id = 'test_q14_rand_text', answer = random_text_lst)

"""## 1.5 Writing Shakespeare [6 points]

Now you can train a language model. We have provided this corpus of Shakespeare at `shakespeare_input.txt` (if you cannot find it, re-run the `Setup 2: Dataset / Packages` section).

We’ve also given you the function `create_ngram_model(model_class, path, n, k)` that will create and return an n-gram model trained on the entire file path provided and `create_ngram_model_lines(model_class, path, n, k)` that will create and return an n-gram model trained line-by-line on the file path provided. You should use the first for the Shakespeare file and the second for the city name files.

Try generating some Shakespeare with different order n-gram models. You should try running the following commands:

```python
>>> m = create_ngram_model(NgramModel, 'shakespeare_input.txt', 2)
>>> m.random_text(250)

>>> m = create_ngram_model(NgramModel, 'shakespeare_input.txt', 3)
>>> m.random_text(250)

>>> m = create_ngram_model(NgramModel, 'shakespeare_input.txt', 4)
>>> m.random_text(250)

>>> m = create_ngram_model(NgramModel, 'shakespeare_input.txt', 7)
>>> m.random_text(250)
```

What do you think? Is it as good as [1000 monkeys working at 1000 typewriters](https://www.youtube.com/watch?v=no_elVGGgW8)?

After generating a bunch of short passages, do you notice anything? *They all start with F!* In fact, after we hit a certain order, the first word is always *First*?  Why is that? Is the model trying to be clever? Is it saying *First, I will generate the word "First"*?  No, probably not.  Explain what is going on in your writeup.

- **Answer 1.5:** Generate Shakespear texts with at least 3 numbers of n and discuss on the results [6 points]
  - Write your response to this in your pdf
"""

## DO NOT CHANGE ##
def create_ngram_model(model_class, path, n=2, k=0):
    ''' Creates and returns a new n-gram model trained on the city names
        found in the path file '''
    model = model_class(n, k)
    with open(path, encoding='utf-8', errors='ignore') as f:
        model.update(f.read())
    return model

def create_ngram_model_lines(model_class, path, n=2, k=0):
    ''' Creates and returns a new n-gram model trained on the city names
        found in the path file '''
    model = model_class(n, k)
    with open(path, encoding='utf-8', errors='ignore') as f:
        for line in f:
            model.update(line.strip())
    return model

# Example
m = create_ngram_model(NgramModel, 'shakespeare_input.txt', 7)
m.random_text(250)

m7 = create_ngram_model(NgramModel, 'shakespeare_input.txt', 7)
len(m7.contexts)

m = create_ngram_model(NgramModel, 'shakespeare_input.txt', 2)
m.random_text(250)

m2 = create_ngram_model(NgramModel, 'shakespeare_input.txt', 2)
len(m2.contexts.keys())

m = create_ngram_model(NgramModel, 'shakespeare_input.txt', 3)
m.random_text(250)

m3 = create_ngram_model(NgramModel, 'shakespeare_input.txt', 3)
len(m3.contexts.keys())

m = create_ngram_model(NgramModel, 'shakespeare_input.txt', 4)
m.random_text(250)

m4 = create_ngram_model(NgramModel, 'shakespeare_input.txt', 4)
len(m4.contexts.keys())

model1 = create_ngram_model(NgramModel, 'shakespeare_input.txt', 2, 1)
model1.contexts

modelline1 = create_ngram_model_lines(NgramModel, 'shakespeare_input.txt', 2, 1)
modelline1.contexts

modelline2 = create_ngram_model_lines(NgramModel, 'shakespeare_input.txt', 3, 1)

modelline2.perplexity("Second Citizen")

modelline2.perplexity("First Citizen")

modelline3 = create_ngram_model_lines(NgramModel, 'shakespeare_input.txt', 4, 1)

text = "First Citizen"
perplexity = modelline1.perplexity(text)
perplexity

text = "Second Citizen"
perplexity = modelline1.perplexity(text)
perplexity

text = "First Citizen"
perplexity = modelline2.perplexity(text)
perplexity

text = "Second Citizen"
perplexity = modelline2.perplexity(text)
perplexity

model1 = create_ngram_model(NgramModel, 'shakespeare_input.txt', 2, 1)
model1.contexts

modelline1_3 = create_ngram_model_lines(NgramModel, 'shakespeare_input.txt', 2, 2.0)



modelline1_4 = modelline1_3
modelline1_4.perplexity("Against him first:")

modelline1_5 = create_ngram_model_lines(NgramModel, 'shakespeare_input.txt', 2, 3.0)

modelline1_5.perplexity("Against him first:")

model2 = create_ngram_model(NgramModel, 'shakespeare_input.txt', 3, 1)
text = "Note me this, good friend;"
perplexity = model1.perplexity(text)
perplexity

## Answer 1.5 in your PDF

"""# Section 2: Smoothing, Perplexity, and Interpolation [30 points]

In this part of the assignment, you'll adapt your code in order to implement several of the  techniques described in [Section 3.5 of the Jurafsky and Martin textbook](https://web.stanford.edu/~jurafsky/slp3/3.pdf).

## 2.1 Smoothing [6 points]

Laplace Smoothing is described in section 3.5.1 of the book. Laplace smoothing adds one to each count (hence its alternate name *add-one smoothing*). Since there are *V* characters in the vocabulary and each one was incremented, we also need to adjust the denominator to take into account the extra V observations.

$$P_{Laplace}(w_i) = \frac{count_i + 1}{N+|V|}$$

A variant of Laplace smoothing is called *Add-k smoothing* or *Add-epsilon smoothing*. This is described in section *Add-k 3.5.2*.

```python
>>> m = NgramModel(1, 1)
>>> m.update('abab')
>>> m.update('abcd')
>>> m.prob('a', 'a')
0.14285714285714285
>>> m.prob('a', 'b')
0.5714285714285714
>>> m.prob('c', 'd')
0.4
>>> m.prob('d', 'a')
0.25
```

- **Problem 2.1**: Update your `NgramModel` code from Part 1 to implement add-k smoothing. (see comment of `## TODO 2.1`) [6 points]
"""

m = NgramModel(1, 1)
m.update('abab')
m.update('abcd')
m.prob('a', 'a')
m.prob('a', 'b')
m.prob('c', 'd')
m.prob('d', 'a')

m.get_vocab()

# PennGrader - DO NOT CHANGE
smoothing_test_cases = [
    (1, 1, ['abab', 'abcd'], ('b', 'a')),
    (2, 1, ['ababa', 'abcdddd', 'babcdabag'], ('ba', 'b')),
    (3, 2, ['ababa', 'abcdddd', 'babcdabag', 'dbaa', 'dbab'], ('aba', 'b'))
]
smoothing_test_results = []
for i, j, corpus, test_words in smoothing_test_cases:
    nm = NgramModel(i, j)
    for text in corpus:
        nm.update(text)
    smoothing_test_results.append(nm.prob(test_words[0], test_words[1]))

grader.grade(test_case_id = 'test_q21_smoothing', answer = smoothing_test_results)

"""## 2.2 Perplexity [12 points]

How do we know whether a language model is good? There are two basic approaches:
1. Task-based evaluation (also known as **extrinsic** evaluation), where we use the language model as part of some other task, like automatic speech recognition, or spelling correcktion, or an OCR system that tries to covert a professor's messy handwriting into text.
2. **Intrinsic** evaluation: Intrinsic evaluation tries to directly evalute the goodness of the language model by seeing how well the probability distributions that it estimates are able to explain some previously unseen test set.

Here's what the textbook says:

> For an intrinsic evaluation of a language model we need a test set. As with many of the statistical models in our field, the probabilities of an N-gram model come from the corpus it is trained on, the training set or training corpus. We can then measure the quality of an N-gram model by its performance on some unseen data called the test set or test corpus. We will also sometimes call test sets and other datasets that are not in our training sets held out corpora because we hold them out from the training data.

> So if we are given a corpus of text and want to compare two different N-gram models, we divide the data into training and test sets, train the parameters of both models on the training set, and then compare how well the two trained models fit the test set.

> But what does it mean to "fit the test set"? The answer is simple: whichever model assigns a higher probability to the test set is a better model.

We'll implement the most common method for intrinsic metric of language models: *perplexity*.  The perplexity of a language model on a test set is the inverse probability of the test set, normalized by the number of characters. For a test set $W = w_1 w_2 ... w_N$:

$$Perplexity(W) = P(w_1 w_2 ... w_N)^{-\frac{1}{N}}$$

$$ = \sqrt[N]{\frac{1}{P(w_1 w_2 ... w_N)}}$$

$$ = \sqrt[N]{\prod_{i=1}^{N}{\frac{1}{P(w_i \mid w_1 ... w_{i-1})}}}$$

Now implement the `perplexity(self, text)` function in `NgramModel`. A couple of things to keep in mind:
1. Numeric underflow is going to be a problem, so consider using logs.
2. Perplexity is undefined if the language model assigns any zero probabilities to the test set. In that case your code should return positive infinity - `float('inf')`.
3. On your unsmoothed models, you'll definitely get some zero probabilities for the test set. To test you code, you should try computing perplexity on the training set, and you should compute perplexity for your language models that use smoothing and interpolation.

```python
>>> m = NgramModel(1, 0)
>>> m.update('abab')
>>> m.update('abcd')
>>> m.perplexity('abcd')
1.189207115002721
>>> m.perplexity('abca')
inf
>>> m.perplexity('abcda')
1.515716566510398
```
"""

m = NgramModel(2, 0)

for text in ['ababa', 'abcdddd', 'babcdabag']:
    m.update(text)

m.contexts

result = m.perplexity('ba')
result

# PennGrader - DO NOT CHANGE rjiang
ppl_test_cases = [
    (1, 0, ['abab', 'abcd'], 'abca'),
    (2, 0, ['ababa', 'abcdddd', 'babcdabag'], 'ba'),
    (3, 1, ['ababa', 'abcdddd', 'babcdabag', 'dbaa', 'dbab'], 'abcdddddddddd')
]
ppl_test_results = []
for i, j, corpus, test_words in ppl_test_cases:
    nm = NgramModel(i, j)
    for text in corpus:
        nm.update(text)
    ppl_test_results.append(nm.perplexity(test_words))

ppl_test_results

"""- **Problem 2.2**: implement the `perplexity(self, text)` function in `NgramModel` [6 points]"""

# PennGrader - DO NOT CHANGE
ppl_test_cases = [
    (1, 0, ['abab', 'abcd'], 'abca'),
    (2, 0, ['ababa', 'abcdddd', 'babcdabag'], 'ba'),
    (3, 1, ['ababa', 'abcdddd', 'babcdabag', 'dbaa', 'dbab'], 'abcdddddddddd')
]
ppl_test_results = []
for i, j, corpus, test_words in ppl_test_cases:
    nm = NgramModel(i, j)
    for text in corpus:
        nm.update(text)
    ppl_test_results.append(nm.perplexity(test_words))

grader.grade(test_case_id = 'test_q22_ppl', answer = ppl_test_results)

"""- **Answer 2.2:** Compare and discuss the perplexity for text that is similar and different from Shakespeare's plays. We provide you two dev text files, a New York Times article (`nytimes_article.txt`) and several of Shakespeare's sonnets (`shakespeare_sonnets.txt`); if you cannot find them, re-run `Setup 2: Dataset / Package` at the beginning. Also, feel free to experiment with your own text. [6 points]"""

## Answer 2.2 in your PDF

"""## 2.3 Interpolation [12 points]

The idea of interpolation is to calculate the higher order n-gram probabilities also combining the probabilities for lower-order n-gram models. Like smoothing, this helps us avoid the problem of zeros if we haven't observed the longer sequence in our training data. Here's the math:

$$P_{interpolation}(w_i|w_{i−2} w_{i−1}) = \lambda_1 P(w_i|w_{i−2} w_{i−1}) + \lambda_2 P(w_i|w_{i−1}) + \lambda_3 P(w_i)$$

where $\lambda_1 + \lambda_2 + \lambda_3 = 1$.

We've provided you with another class definition `NgramModelWithInterpolation` that extends `NgramModel` for you to implement interpolation. If you've written your code robustly, you should only need to override the `get_vocab(self)`, `update(self, text)`, and `prob(self, context, char)` methods, along with the initializer.

The value of $n$ passed into `__init__(self, n, k)` is the highest order n-gram to be considered by the model (e.g. $n=2$ will consider 3 different length n-grams). Add-k smoothing should take place only when calculating the individual order n-gram probabilities, not when calculating the overall interpolation probability.

By default set the lambdas to be equal weights, but you should also write a helper function that can be called to overwrite this default. Setting the lambdas in the helper function can either be done heuristically or by using a development set, but in the example code below, we've used the default.

```python
>>> m = NgramModelWithInterpolation(1, 0)
>>> m.update('abab')
>>> m.prob('a', 'a')
0.25
>>> m.prob('a', 'b')
0.75

>>> m = NgramModelWithInterpolation(2, 1)
>>> m.update('abab')
>>> m.update('abcd')
>>> m.prob('~a', 'b')
0.4682539682539682
>>> m.prob('ba', 'b')
0.4349206349206349
>>> m.prob('~c', 'd')
0.27222222222222225
>>> m.prob('bc', 'd')
0.3222222222222222
```
- **Problem 2.3**: implement the `NgramModelWithInterpolation` class [6 points]
"""

m = NgramModel(1, 0)
m.update('abab')
m.contexts

import math

class NgramModelWithInterpolation(NgramModel):
    ''' An n-gram model with interpolation '''

    def __init__(self, n, k):
        ## TODO 2.3
        self.n = n
        self.k = k
        self.num_model = n + 1

        self.models = [] # the first is unigram
        self.lambdas = [] # the length is either 1, 2, or 3. Maximum is 3.
        self.vocab = []
        for i in range(self.n+1):
            self.lambdas.append(1/(self.n+1))
            self.models.append(dict())
            self.vocab.append(set())

    def get_vocab(self):
        ## TODO 2.3
        return self.vocab

    def update(self, text):
        ## TODO 2.3
        for i in range(self.n+1):
            contexts = self.models[i]
            vocab = self.vocab[i]
            if i == 0:
                if '' in contexts:
                    contexts[''][COUNT_KEY] = contexts[''][COUNT_KEY] + len(text)
                else:
                    contexts[''] = dict()
                    contexts[''][COUNT_KEY] = len(text)
                    contexts[''][CHARS_KEY] = defaultdict(int)
                for letter in text:
                    contexts[''][CHARS_KEY][letter] = contexts[''][CHARS_KEY][letter] + 1
            else:
                ngrams_context = ngrams(i, text)
                for ngram_item in ngrams_context:
                    pre_context, cur_letter = ngram_item
                    if pre_context in contexts:
                        contexts[pre_context][COUNT_KEY] += 1
                    else:
                        contexts[pre_context] = dict()
                        contexts[pre_context][COUNT_KEY] = 1
                        contexts[pre_context][CHARS_KEY] = defaultdict(int)
                    contexts[pre_context][CHARS_KEY][cur_letter] += 1
            for key, value in contexts.items():
                vocab.update(value[CHARS_KEY].keys())

    def prob(self, context, char):
        ## TODO 2.3
        probability = 0
        context_input = context
        for i in range(self.n+1):
            context = context_input[0-i:]
            if i == 0:
                context = ''
            # print("sub context is [{}]".format(context))
            vocab = self.vocab[i]
            cur_prob = 0
            contexts = self.models[i]
            if self.k == 0:
                if context not in contexts:
                    cur_prob = 1/(len(self.get_vocab()))
                else:
                    context_count = contexts[context][COUNT_KEY]
                    char_count = contexts[context][CHARS_KEY][char]
                    cur_prob = char_count / context_count
            else:
                if context not in contexts:
                    cur_prob = 1/(len(vocab))
                else:
                    v_count = len(vocab)
                    sum_n = 0
                    char_count = self.k
                    for key in contexts[context][CHARS_KEY]:
                        if key == char:
                            char_count += contexts[context][CHARS_KEY][key]
                        sum_n += contexts[context][CHARS_KEY][key]
                    cur_prob = char_count / (sum_n + self.k * v_count)
            # print("i is {} cur_prob is {}".format(i, cur_prob))
            probability += self.lambdas[i] * cur_prob

        return probability

    def perplexity(self, text):
        # print("perplexity")
        ''' Returns the perplexity of text based on the n-grams learned by
            this model '''
        ## TODO 2.2 - see problem 2.2
        # return 0.56
        grams = ngrams(self.n, text)
        # print("grams is {}".format(grams))
        sum = 0

        for gram in grams:
            prob = self.prob(gram[0], gram[1])
            # print("prob is {}".format(prob))
            if prob == 0.0:
                continue
            log_new = math.log2(prob)
            sum += log_new
        avg = sum / len(grams)
        # print("avg is {} len of gram is {}".format(avg, len(grams)))
        return math.pow(2, 0 - avg)

# PennGrader - DO NOT CHANGE
interpolation_test_cases = [
    [(0, 1), ['abab'], ('a', 'a')],
    [(2, 1), ['abab', 'abcd'], ('~c', 'd')],
    [(2, 1), ['abeadab', 'abcd', 'eadb'], ('~a','b')],
    [(2, 1), ['abab', 'abcd', 'aaaaad'], ('bc', 'd')],
]

interpolation_test_results = []
for (n, k), corpus, (context, char) in interpolation_test_cases:
    nm_interpolation = NgramModelWithInterpolation(n, k)
    for text in corpus:
        nm_interpolation.update(text)
    interpolation_test_results.append(nm_interpolation.prob(context, char))

grader.grade(test_case_id = 'test_q23_interpolation', answer = interpolation_test_results)

interpolate_modelline1_3 = create_ngram_model_lines(NgramModelWithInterpolation, 'shakespeare_input.txt', 2, 1)
interpolate_modelline1_3.perplexity("Against him first:")

interpolate_modelline1_5 = create_ngram_model_lines(NgramModelWithInterpolation, 'shakespeare_input.txt', 2, 3.0)
interpolate_modelline1_5.perplexity("Against him first:")

lambda_model_1 = create_ngram_model_lines(NgramModelWithInterpolation, 'shakespeare_input.txt', 3, 1.0)

"""- **Answer 2.3**: Experiment with a few different lambdas and values of k and discuss the effects of smoothing and interpolation in terms of perplexity. Alternatively, you can also try different number of n. You may still use text files from 2.2. [6 points]


"""

## Answer 2.3 in your PDF

"""# Section 3: Text Classification using N-Grams [20 points + 5 bonus]
**No PennGrader in this section, see `Deliverables` for grading details**
## Overview
Language models can be applied to text classification. If we want to classify a text $D$ into a category $c \in C={c_1, ..., c_N}$. We can pick the category $c$ that has the largest posterior probability given the text. That is,

$$ c^* = arg max_{c \in C} P(c|D) $$

Using Bayes rule, this can be rewritten as:

$$ c^* = arg max_{c \in C} P(D|c) P(c)$$

If we assume that all classes are equally likely, then we can just drop the $P(c)$ term:

$$ = arg max_{c \in C} P(D|c)$$

Here $P(D \mid c)$ is the likelihood of $D$ under category $c$, which can be computed by training language models for all texts associated with category $c$. This technique of text classification is drawn from [literature on authorship identification](http://www.aclweb.org/anthology/E/E03/E03-1053.pdf), where the approach is to learn a separate language model for each author, by training on a data set from that author. Then, to categorize a new text D, they use each language model to calculate the likelihood of D under that model, and pick the  category that assigns the highest probability to D.


## Try it!
We have provided you training and validation datsets consisting of the names of cities. The task is to predict the country a city is in. The following countries are including in the dataset.

```
af	Afghanistan
cn	China
de	Germany
fi	Finland
fr	France
in	India
ir	Iran
pk	Pakistan
za	South Africa
```

We'll set up a leaderboard for the text classification task. **Your job is to configure a set of language models that perform the best on the text classification task.** We will use the `city names` dataset, which you should have already downloaded. The test set has one unlabeled city name per line.

Your code should output a file `test_labels.txt` with one two-letter country code per line.

Feel free to extend the `NgramModel` or `NgramModelWithInterpolation` when creating your language model. Possible ideas to consider and experiment with when creating your model are utilizing a special end-of-text character, trying a new method for determining the vocab, and improving how your model handles novel characters.

## Deliverables
- **Answer 3.1:** Train your best model on the given training data (located in `train` folder), and report accuracy on the given validation data (located in `val` folder) for your final model. In order to receive full credit, your model must be able to outperform all the baselines. [5 points]

- **Answer 3.2:** Describe the parameters you used for the final submission, such as n , k and interpolation. Discuss how you made the decision and why your combination have better results, we encourage using a table to display all validation accuracies of your experiment process. Be sure to include a detailed error analysis: identify several examples of cities on which your final model is making errors, discuss potential reasons. [15 points]

- **Answer 3.3:** Make predictions on the given test data (`cities_test.txt`) and upload `test_labels.txt` to Gradescope, which contains one two-letter country code per line. Please note that testing accuracy should be valid and outperform the baseline in order to receive full credits (included in 3.1). Top 3 will be granted 5 bonus points.
"""

COUNTRY_CODES = ['af', 'cn', 'de', 'fi', 'fr', 'in', 'ir', 'pk', 'za']

from zipfile import ZipFile
import io
import numpy as np

city_name_per_80_length = dict()

with ZipFile('cities_train.zip') as zip_ref:
    for country_code in COUNTRY_CODES:
        file_name = "train/{}.txt".format(country_code)
        with  zip_ref.open(file_name) as binary_file:
            with io.TextIOWrapper(binary_file, encoding='utf-8', errors="ignore") as text_file:
                city_name_length = []
                for line in text_file:
                    city_name_length.append(len(line))
                city_name_per_80_length[country_code] = int(np.percentile(city_name_length, 80))
                print("country {} percentile {}".format(country_code, np.percentile(city_name_length, 80)))

# training the model
from zipfile import ZipFile
import io
import numpy as np

city_name_per_80_length = dict()
country_to_model = dict()

for country_code in COUNTRY_CODES:
    # country_to_model[country_code] = NgramModelWithInterpolation(city_name_per_80_length[country_code], 0)
    country_to_model[country_code] = NgramModelWithInterpolation(2, 0)

with ZipFile('cities_train.zip') as zip_ref:
    for country_code in COUNTRY_CODES:
        file_name = "train/{}.txt".format(country_code)
        with  zip_ref.open(file_name) as binary_file:
            with io.TextIOWrapper(binary_file, encoding='utf-8', errors="ignore") as text_file:
                nm_model = country_to_model[country_code]
                for line in text_file:
                    nm_model.update(line)

with ZipFile('cities_train.zip') as zip_ref:

# evaluate the perplexity  by using val.zip
with ZipFile('cities_val.zip') as zip_ref:
    # file_list = zip_ref.namelist()
    for country_code in COUNTRY_CODES:
        file_name = "val/{}.txt".format(country_code)
        nm_model = country_to_model[country_code]
        total_perplexity = 0
        count = 0
        with zip_ref.open(file_name) as binary_file:
            with io.TextIOWrapper(binary_file, encoding='utf-8', errors="ignore") as text_file:
                for line in text_file:
                    count += 1
                    # print("country_code {} line is {}".format(country_code, line))
                    total_perplexity += nm_model.perplexity(line)
                avg_perplexity = total_perplexity / count
                print("avg_perplexity {}".format(avg_perplexity))

# for each country find the best one
def train_zip(country_code, n, k):
    # print("country_code {}".format(country_code))
    file_name = "train/{}.txt".format(country_code)
    # print('file_name is {}'.format(file_name))
    nm_model = NgramModelWithInterpolation(n, k)
    with ZipFile('cities_train.zip') as zip_ref:
         with zip_ref.open(file_name) as binary_file:
            with io.TextIOWrapper(binary_file, encoding='utf-8', errors="ignore") as text_file:
                for line in text_file:
                    nm_model.update(line)

    file_name = "val/{}.txt".format(country_code)
    count = 0
    total_perplexity = 0
    with ZipFile('cities_val.zip') as zip_ref:
         with zip_ref.open(file_name) as binary_file:
            with io.TextIOWrapper(binary_file, encoding='utf-8', errors="ignore") as text_file:
                for line in text_file:
                    count += 1
                    total_perplexity += nm_model.perplexity(line)
                avg_perplexity = total_perplexity / count
    return avg_perplexity

k = 0
for country_code in COUNTRY_CODES:
    min_perplexity = 100
    min_n = -1
    min_k = -1
    for n in range(9):
        avg_perplexity = train_zip(country_code, n, k)
        if avg_perplexity < min_perplexity:
            min_n = n
            min_k = k
            min_perplexity = avg_perplexity
    print("country code {} n is {} k is {} perplexity is {}".format(country_code, min_n, min_k, min_perplexity))

# for each country find the best one
# train 2
def train_zip(country_code, n, k):
    # print("country_code {}".format(country_code))
    file_name = "train/{}.txt".format(country_code)
    # print('file_name is {}'.format(file_name))
    nm_model = NgramModelWithInterpolation(n, k)
    with ZipFile('cities_train.zip') as zip_ref:
         with zip_ref.open(file_name) as binary_file:
            with io.TextIOWrapper(binary_file, encoding='utf-8', errors="ignore") as text_file:
                for line in text_file:
                    nm_model.update(line)

    file_name = "val/{}.txt".format(country_code)
    count = 0
    total_perplexity = 0
    with ZipFile('cities_val.zip') as zip_ref:
         with zip_ref.open(file_name) as binary_file:
            with io.TextIOWrapper(binary_file, encoding='utf-8', errors="ignore") as text_file:
                for line in text_file:
                    count += 1
                    total_perplexity += nm_model.perplexity(line)
                avg_perplexity = total_perplexity / count
    return avg_perplexity

min_perplexity = 100
min_n = -1
min_k = -1
country_code = 'de'
for n in range(10):
    k = 0
    avg_perplexity = train_zip(country_code, n, k)
    if avg_perplexity < min_perplexity:
        min_n = n
        min_k = k
        min_perplexity = avg_perplexity
print("country code {} n is {} k is {} perplexity is {}".format(country_code, min_n, min_k, min_perplexity))

country_code = 'cn'
avg_perplexity = train_zip(country_code, 7, 0)
avg_perplexity

country_code = 'af'
avg_perplexity = train_zip(country_code, 7, 0)
avg_perplexity

# country_code['af', 'cn', 'de', 'fi', 'fr', 'in', 'ir', 'pk', 'za']
country_models = dict()
country_models['af'] = NgramModelWithInterpolation(6, 0)
country_models['cn'] = NgramModelWithInterpolation(5, 0)
country_models['de'] = NgramModelWithInterpolation(6, 0)
country_models['fi'] = NgramModelWithInterpolation(6, 0)
country_models['fr'] = NgramModelWithInterpolation(6, 0)
country_models['in'] = NgramModelWithInterpolation(6, 0)
country_models['ir'] = NgramModelWithInterpolation(6, 0)
country_models['pk'] = NgramModelWithInterpolation(6, 0)
country_models['za'] = NgramModelWithInterpolation(6, 0)

results = dict() # element is [], key is country code
for country_code in COUNTRY_CODES:
    results[country_code] = []

with ZipFile('cities_val.zip') as zip_ref:
         with zip_ref.open(file_name) as binary_file:
            with io.TextIOWrapper(binary_file, encoding='utf-8', errors="ignore") as text_file:
                for line in text_file:
                    min_perplexity = 100.0
                    min_country_code = 'af'
                    for country_code in country_models.keys():
                        nm_model = country_models[country_code]
                        perplexity = nm_model.perplexity(line)
                        if min_perplexity > perplexity:
                            min_perplexity = perplexity
                            min_country_code = country_code
                    results.append(min_country_code)

with open('cities_test.txt', 'r', encoding='utf-8', errors="ignore") as f:
    lines = f.readlines()
    for line in lines:
        min_perplexity = 100.0
        min_country_code = 'af'
        for country_code in country_models.keys():
            nm_model = country_models[country_code]
            perplexity = nm_model.perplexity(line)
            if min_perplexity > perplexity:
                min_perplexity = perplexity
                min_country_code = country_code
        results.append(min_country_code)

# country_code['af', 'cn', 'de', 'fi', 'fr', 'in', 'ir', 'pk', 'za']
country_models = dict()
country_models['af'] = NgramModelWithInterpolation(6, 0)
country_models['cn'] = NgramModelWithInterpolation(5, 0)
country_models['de'] = NgramModelWithInterpolation(5, 0)
country_models['fi'] = NgramModelWithInterpolation(5, 0)
country_models['fr'] = NgramModelWithInterpolation(5, 0)
country_models['in'] = NgramModelWithInterpolation(5, 0)
country_models['ir'] = NgramModelWithInterpolation(5, 0)
country_models['pk'] = NgramModelWithInterpolation(5, 0)
country_models['za'] = NgramModelWithInterpolation(5, 0)

count = 1
results = []
with open('cities_test.txt', 'r', encoding='utf-8', errors="ignore") as f:
    lines = f.readlines()
    for line in lines:
        min_perplexity = 100.0
        min_country_code = 'af'
        for country_code in country_models.keys():
            nm_model = country_models[country_code]
            perplexity = nm_model.perplexity(line)
            if min_perplexity > perplexity:
                min_perplexity = perplexity
                min_country_code = country_code
        results.append(min_country_code)

print(results)

## Answer 3.1 and 3.2 in your PDF ###

"""# Submission
### Congratulation on finishing your homework! Here are the deliverables you need to submit to GradeScope
- This notebook and py file: rename to `homework3.ipynb` and `homework3.py`. You can download the notebook and py file by going to the top-left corner of this webpage, `File -> Download -> Download .ipynb/.py`
- Your `report.pdf`
  - including answers to 1.5, 2.2, 2.3, 3.1, and 3.2
- `test_labels.txt` from `Section 3`
"""